/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE, modified for STM32F103C8T6
 * @brief          : Main program body with CAN in loopback mode
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// Register definitions for STM32F103C8T6
#define RCC_CR 			 (*(volatile uint32_t *)0x40021000)
#define RCC_CFGR     	 (*(volatile uint32_t *)0x40021004)
#define RCC_APB1ENR      (*(volatile uint32_t *)0x4002101C)
#define RCC_APB2ENR      (*(volatile uint32_t *)0x40021018)
#define RCC_AHBENR       (*(volatile uint32_t *)0x40021014)
#define GPIOA_CRL        (*(volatile uint32_t *)0x40010800)
#define GPIOA_CRH        (*(volatile uint32_t *)0x40010804)
#define FLASH_ACR        (*(volatile uint32_t *)0x40022000)
#define SYST_CSR         (*(volatile uint32_t *)0xE000E010)
#define SYST_RVR         (*(volatile uint32_t *)0xE000E014)
#define SYST_CVR         (*(volatile uint32_t *)0xE000E018)
#define CAN_MCR          (*(volatile uint32_t *)0x40006400)
#define CAN_MSR          (*(volatile uint32_t *)0x40006404)
#define CAN_TSR          (*(volatile uint32_t *)0x40006408)
#define CAN_RF0R         (*(volatile uint32_t *)0x4000640C)
#define CAN_RF1R         (*(volatile uint32_t *)0x40006410)
#define CAN_IER          (*(volatile uint32_t *)0x40006414)
#define CAN_ESR          (*(volatile uint32_t *)0x40006418)
#define CAN_BTR          (*(volatile uint32_t *)0x4000641C)
#define CAN_TI0R         (*(volatile uint32_t *)0x40006580)
#define CAN_TDT0R        (*(volatile uint32_t *)0x40006584)
#define CAN_TDL0R        (*(volatile uint32_t *)0x40006588)
#define CAN_TDH0R        (*(volatile uint32_t *)0x4000658C)
#define CAN_TI1R         (*(volatile uint32_t *)0x40006590)
#define CAN_TDT1R        (*(volatile uint32_t *)0x40006594)
#define CAN_TDL1R        (*(volatile uint32_t *)0x40006598)
#define CAN_TDH1R        (*(volatile uint32_t *)0x4000659C)
#define CAN_TI2R         (*(volatile uint32_t *)0x400065A0)
#define CAN_TDT2R        (*(volatile uint32_t *)0x400065A4)
#define CAN_TDL2R        (*(volatile uint32_t *)0x400065A8)
#define CAN_TDH2R        (*(volatile uint32_t *)0x400065AC)
#define CAN_RDL0R        (*(volatile uint32_t *)0x400065B8)
#define CAN_FMR          (*(volatile uint32_t *)0x40006600)
#define CAN_FM1R         (*(volatile uint32_t *)0x40006604)
#define CAN_FS1R         (*(volatile uint32_t *)0x4000660C)
#define CAN_FFA1R        (*(volatile uint32_t *)0x40006614)
#define CAN_FA1R         (*(volatile uint32_t *)0x4000661C)
#define CAN_F0R1         (*(volatile uint32_t *)0x40006640)
#define CAN_F0R2         (*(volatile uint32_t *)0x40006644)
#define USART_SR         (*(volatile uint32_t *)0x40013800)
#define USART_DR         (*(volatile uint32_t *)0x40013804)
#define USART_BRR        (*(volatile uint32_t *)0x40013808)
#define USART_CR1        (*(volatile uint32_t *)0x4001380C)

#define F_CPU 64000000
#define BAUD_RATE 9600


 void USART1_Init(void);
 void USART1_BaudRate(void);
 void USART1_SendChar(char c);
 void USART1_SendString(const char *str);
void SystemClock_Config(void);
void GPIO_Init(void);
void delay_ms(uint32_t ms);
void SysTick_Init(void);
void can_Initialize(void);
void can_send(void);
unsigned char can_receive(void);



void SystemClock_Config(void) {
 RCC_CR |= (1<<0);
 while(!(RCC_CR & (1<<1)));
 FLASH_ACR |= (1 << 1);
 FLASH_ACR |=(1<<4);
 while(!(FLASH_ACR & (1<<5)));
 RCC_CFGR &= ~(1<<16);
 RCC_CFGR |= (1<<18)|(1<<19)|(1<<20)|(1<<21);
 RCC_CR |= (1<<24);
 while(!(RCC_CR & (1<<25)));
 RCC_CFGR |= (1<<1);
 while(!(RCC_CFGR & (1<<3)));
 RCC_CFGR &= ~((1<<7)|(1<<10)|(1<<13));
 RCC_AHBENR |= (1<<10);


}


void GPIO_Init(void){
	RCC_APB2ENR |=(1<<2)|(1<<0);
	RCC_APB1ENR |= (1 << 25);
   GPIOA_CRH &= ~(0Xff<<12);
   GPIOA_CRH |= (0XB4<<12);


}


void can_Initialize(void) {
    CAN_MCR |= (1 << 0);
    while (!(CAN_MSR & (1 << 0)));
    CAN_MCR &= ~(1 << 1);
    CAN_BTR |= (1 << 30);
    CAN_BTR = (1 << 30) | (4 << 20) | (13 << 16) | (3 << 0);
    CAN_FMR |= (1 << 0);
    CAN_FA1R |= (1 << 0);
    CAN_FM1R &= ~(1 << 0);
    CAN_FS1R |= (1 << 0);
    CAN_F0R1 = 0;
    CAN_F0R2 = 0;
    CAN_FMR &= ~(1 << 0);
    CAN_MCR &= ~(1 << 0);
    while (CAN_MSR & (1 << 0));
}

void can_send(void) {
    while (!(CAN_TSR & (1 << 26)));
    CAN_TI0R = (0x123 << 21);
    CAN_TDT0R = 1;
    CAN_TDL0R = 0x04;
    CAN_TI0R |= (1 << 0);
    while (!(CAN_TSR & (1 << 0)));
}

unsigned char can_receive(void) {
    uint32_t timeout = 1000000;
    while (!(CAN_RF0R & 0x3) && timeout--);
    if (timeout == 0) return 0;
    unsigned char data = CAN_RDL0R & 0xFF;
    CAN_RF0R |= (1 << 5);
    return data;
}




void SysTick_Init(void) {
	SYST_RVR = 8000 - 1;
	SYST_CVR = 0;
	SYST_CSR &= ~(1 << 2);
	SYST_CSR |= (1<<0);
}
void delay_ms(uint32_t ms) {
SYST_CVR = 0;
	for (uint32_t i = 0; i < ms; i++) {
	        while (!(SYST_CSR & (1 << 16)));
    }
}

void USART1_Init(void){
	RCC_APB2ENR |=(1<<2)|(1<<14);
	GPIOA_CRH |=(1<<4)|(1<<5)|(1<<7)|(1<<10);
	GPIOA_CRH &= ~((1<<6)|(1<<8)|(1<<9)|(1<<11));
	USART1_BaudRate();
   USART_CR1 |= (1 << 13) | (1 << 3) | (1 << 2)|(1<<5);
   USART_CR1 &= ~(1 << 10);

}
void USART1_BaudRate(void){
	     uint32_t USARTDIV = F_CPU/(16*BAUD_RATE);
	 	 uint32_t mantissa = (uint32_t)USARTDIV;
	 	 uint32_t fraction = (uint32_t)((USARTDIV-mantissa)*16);
	 	 USART_BRR = (mantissa<<4)|fraction;

}
void USART1_SendChar(char c) {
    USART_DR = c;
    while (!(USART_SR & (1 << 7)));
    while (!(USART_SR & (1 << 6)));

}
void USART1_SendString(const char *str) {
    while (*str) {
        USART1_SendChar(*str++);
    }
}

int main(void) {
    SystemClock_Config();
    GPIO_Init();
    SysTick_Init();
    USART1_Init();
    can_Initialize();
    USART1_SendChar('A');
    while (1) {
    	char  buffer[2];
        can_send();
        USART1_SendChar('S');
        unsigned char received = can_receive();
        sprintf(buffer,"%d",received);
        USART1_SendString(buffer);

        delay_ms(100);
    }
}
